apiVersion: apps/v1
kind: Deployment
metadata:
  name: transaction-check
spec:
  replicas: 2
  selector:
    matchLabels:
      app: transaction-check
  template:
    metadata:
      labels:
        app: transaction-check
    spec:
      containers:
      - name: transaction-check
        image: taniajose95/transaction_check:${IMAGE_TAG}
        env:
        - name: MYSQL_HOST
          value: "localhost"
        - name: MYSQL_USER
          value: "root"
        - name: MYSQL_PASSWORD
          value: "Lebanon@123"
        - name: MYSQL_DB
          value: "transaction_db"
        ports:
        - containerPort: 5000
---
apiVersion: v1
kind: Service
metadata:
  name: transaction-check-service
spec:
  type: LoadBalancer
  ports:
    - port: 80
      targetPort: 5000
  selector:
    app: transaction-check

